/** Human-readable labels for all item IDs used in recipes. */
export const ITEM_LABELS: Record<string, string> = {
  plank: 'Plank',
  stick: 'Stick',
  cobblestone: 'Cobblestone',
  iron_ingot: 'Iron Ingot',
  gold_ingot: 'Gold Ingot',
  diamond: 'Diamond',
  string: 'String',
  leather: 'Leather',
  paper: 'Paper',
  book: 'Book',
  sugar_cane: 'Sugar Cane',
  wheat: 'Wheat',
  red_mushroom: 'Red Mushroom',
  brown_mushroom: 'Brown Mushroom',
  bowl: 'Bowl',
  feather: 'Feather',
  flint: 'Flint',
  redstone: 'Redstone',
  glass: 'Glass',
  obsidian: 'Obsidian',
  bone: 'Bone',
  melon_slice: 'Melon Slice',
  pumpkin: 'Pumpkin',
  snow_block: 'Snow Block',
  coal: 'Coal',
  wood: 'Wood',
  sand: 'Sand',
  gunpowder: 'Gunpowder',
  blaze_powder: 'Blaze Powder',
  ender_pearl: 'Ender Pearl',
  glass_bottle: 'Glass Bottle',
  nether_wart: 'Nether Wart',
  glowstone_dust: 'Glowstone Dust',
  iron_nugget: 'Iron Nugget',
  gold_nugget: 'Gold Nugget',
  chest: 'Chest',
};

/** All item IDs available as decoy materials. */
export const ALL_ITEM_IDS = Object.keys(ITEM_LABELS);
