import { Recipe } from './types';

const recipes: Recipe[] = [
  // === EASY RECIPES ===
  {
    id: 'wooden_planks',
    type: 'shapeless',
    label: 'Wooden Planks',
    ingredients: ['wood'],
    output: 'plank',
    difficulty: 'easy',
  },
  {
    id: 'sticks',
    type: 'shaped',
    label: 'Sticks',
    pattern: [
      ['plank', null, null],
      ['plank', null, null],
      [null, null, null],
    ],
    output: 'stick',
    materials: ['plank'],
    difficulty: 'easy',
  },
  {
    id: 'crafting_table',
    type: 'shaped',
    label: 'Crafting Table',
    pattern: [
      ['plank', 'plank', null],
      ['plank', 'plank', null],
      [null, null, null],
    ],
    output: 'crafting_table',
    materials: ['plank'],
    difficulty: 'easy',
  },
  {
    id: 'chest',
    type: 'shaped',
    label: 'Chest',
    pattern: [
      ['plank', 'plank', 'plank'],
      ['plank', null, 'plank'],
      ['plank', 'plank', 'plank'],
    ],
    output: 'chest',
    materials: ['plank'],
    difficulty: 'easy',
  },
  {
    id: 'wooden_sword',
    type: 'shaped',
    label: 'Wooden Sword',
    pattern: [
      [null, 'plank', null],
      [null, 'plank', null],
      [null, 'stick', null],
    ],
    output: 'wooden_sword',
    materials: ['plank', 'stick'],
    difficulty: 'easy',
  },
  {
    id: 'wooden_pickaxe',
    type: 'shaped',
    label: 'Wooden Pickaxe',
    pattern: [
      ['plank', 'plank', 'plank'],
      [null, 'stick', null],
      [null, 'stick', null],
    ],
    output: 'wooden_pickaxe',
    materials: ['plank', 'stick'],
    difficulty: 'easy',
  },
  {
    id: 'wooden_axe',
    type: 'shaped',
    label: 'Wooden Axe',
    pattern: [
      ['plank', 'plank', null],
      ['plank', 'stick', null],
      [null, 'stick', null],
    ],
    output: 'wooden_axe',
    materials: ['plank', 'stick'],
    difficulty: 'easy',
  },
  {
    id: 'wooden_shovel',
    type: 'shaped',
    label: 'Wooden Shovel',
    pattern: [
      [null, 'plank', null],
      [null, 'stick', null],
      [null, 'stick', null],
    ],
    output: 'wooden_shovel',
    materials: ['plank', 'stick'],
    difficulty: 'easy',
  },
  {
    id: 'bowl',
    type: 'shaped',
    label: 'Bowl',
    pattern: [
      [null, null, null],
      ['plank', null, 'plank'],
      [null, 'plank', null],
    ],
    output: 'bowl',
    materials: ['plank'],
    difficulty: 'easy',
  },
  {
    id: 'mushroom_stew',
    type: 'shapeless',
    label: 'Mushroom Stew',
    ingredients: ['red_mushroom', 'brown_mushroom', 'bowl'],
    output: 'mushroom_stew',
    difficulty: 'easy',
  },
  {
    id: 'torch',
    type: 'shaped',
    label: 'Torch',
    pattern: [
      ['coal', null, null],
      ['stick', null, null],
      [null, null, null],
    ],
    output: 'torch',
    materials: ['coal', 'stick'],
    difficulty: 'easy',
  },
  {
    id: 'furnace',
    type: 'shaped',
    label: 'Furnace',
    pattern: [
      ['cobblestone', 'cobblestone', 'cobblestone'],
      ['cobblestone', null, 'cobblestone'],
      ['cobblestone', 'cobblestone', 'cobblestone'],
    ],
    output: 'furnace',
    materials: ['cobblestone'],
    difficulty: 'easy',
  },

  // === MEDIUM RECIPES ===
  {
    id: 'stone_pickaxe',
    type: 'shaped',
    label: 'Stone Pickaxe',
    pattern: [
      ['cobblestone', 'cobblestone', 'cobblestone'],
      [null, 'stick', null],
      [null, 'stick', null],
    ],
    output: 'stone_pickaxe',
    materials: ['cobblestone', 'stick'],
    difficulty: 'medium',
  },
  {
    id: 'stone_sword',
    type: 'shaped',
    label: 'Stone Sword',
    pattern: [
      [null, 'cobblestone', null],
      [null, 'cobblestone', null],
      [null, 'stick', null],
    ],
    output: 'stone_sword',
    materials: ['cobblestone', 'stick'],
    difficulty: 'medium',
  },
  {
    id: 'stone_axe',
    type: 'shaped',
    label: 'Stone Axe',
    pattern: [
      ['cobblestone', 'cobblestone', null],
      ['cobblestone', 'stick', null],
      [null, 'stick', null],
    ],
    output: 'stone_axe',
    materials: ['cobblestone', 'stick'],
    difficulty: 'medium',
  },
  {
    id: 'iron_pickaxe',
    type: 'shaped',
    label: 'Iron Pickaxe',
    pattern: [
      ['iron_ingot', 'iron_ingot', 'iron_ingot'],
      [null, 'stick', null],
      [null, 'stick', null],
    ],
    output: 'iron_pickaxe',
    materials: ['iron_ingot', 'stick'],
    difficulty: 'medium',
  },
  {
    id: 'iron_sword',
    type: 'shaped',
    label: 'Iron Sword',
    pattern: [
      [null, 'iron_ingot', null],
      [null, 'iron_ingot', null],
      [null, 'stick', null],
    ],
    output: 'iron_sword',
    materials: ['iron_ingot', 'stick'],
    difficulty: 'medium',
  },
  {
    id: 'bow',
    type: 'shaped',
    label: 'Bow',
    pattern: [
      [null, 'stick', 'string'],
      ['stick', null, 'string'],
      [null, 'stick', 'string'],
    ],
    output: 'bow',
    materials: ['stick', 'string'],
    difficulty: 'medium',
  },
  {
    id: 'arrow',
    type: 'shaped',
    label: 'Arrow',
    pattern: [
      [null, 'flint', null],
      [null, 'stick', null],
      [null, 'feather', null],
    ],
    output: 'arrow',
    materials: ['flint', 'stick', 'feather'],
    difficulty: 'medium',
  },
  {
    id: 'paper',
    type: 'shaped',
    label: 'Paper',
    pattern: [
      [null, null, null],
      ['sugar_cane', 'sugar_cane', 'sugar_cane'],
      [null, null, null],
    ],
    output: 'paper',
    materials: ['sugar_cane'],
    difficulty: 'medium',
  },
  {
    id: 'book',
    type: 'shapeless',
    label: 'Book',
    ingredients: ['paper', 'paper', 'paper', 'leather'],
    output: 'book',
    difficulty: 'medium',
  },
  {
    id: 'bread',
    type: 'shaped',
    label: 'Bread',
    pattern: [
      [null, null, null],
      ['wheat', 'wheat', 'wheat'],
      [null, null, null],
    ],
    output: 'bread',
    materials: ['wheat'],
    difficulty: 'medium',
  },
  {
    id: 'bone_meal',
    type: 'shapeless',
    label: 'Bone Meal',
    ingredients: ['bone'],
    output: 'bone_meal',
    difficulty: 'medium',
  },
  {
    id: 'ladder',
    type: 'shaped',
    label: 'Ladder',
    pattern: [
      ['stick', null, 'stick'],
      ['stick', 'stick', 'stick'],
      ['stick', null, 'stick'],
    ],
    output: 'ladder',
    materials: ['stick'],
    difficulty: 'medium',
  },

  // === HARD RECIPES ===
  {
    id: 'diamond_pickaxe',
    type: 'shaped',
    label: 'Diamond Pickaxe',
    pattern: [
      ['diamond', 'diamond', 'diamond'],
      [null, 'stick', null],
      [null, 'stick', null],
    ],
    output: 'diamond_pickaxe',
    materials: ['diamond', 'stick'],
    difficulty: 'hard',
  },
  {
    id: 'diamond_sword',
    type: 'shaped',
    label: 'Diamond Sword',
    pattern: [
      [null, 'diamond', null],
      [null, 'diamond', null],
      [null, 'stick', null],
    ],
    output: 'diamond_sword',
    materials: ['diamond', 'stick'],
    difficulty: 'hard',
  },
  {
    id: 'bookshelf',
    type: 'shaped',
    label: 'Bookshelf',
    pattern: [
      ['plank', 'plank', 'plank'],
      ['book', 'book', 'book'],
      ['plank', 'plank', 'plank'],
    ],
    output: 'bookshelf',
    materials: ['plank', 'book'],
    difficulty: 'hard',
  },
  {
    id: 'tnt',
    type: 'shaped',
    label: 'TNT',
    pattern: [
      ['gunpowder', 'sand', 'gunpowder'],
      ['sand', 'gunpowder', 'sand'],
      ['gunpowder', 'sand', 'gunpowder'],
    ],
    output: 'tnt',
    materials: ['gunpowder', 'sand'],
    difficulty: 'hard',
  },
  {
    id: 'piston',
    type: 'shaped',
    label: 'Piston',
    pattern: [
      ['plank', 'plank', 'plank'],
      ['cobblestone', 'iron_ingot', 'cobblestone'],
      ['cobblestone', 'redstone', 'cobblestone'],
    ],
    output: 'piston',
    materials: ['plank', 'cobblestone', 'iron_ingot', 'redstone'],
    difficulty: 'hard',
  },
  {
    id: 'golden_apple',
    type: 'shaped',
    label: 'Golden Apple',
    pattern: [
      ['gold_ingot', 'gold_ingot', 'gold_ingot'],
      ['gold_ingot', 'melon_slice', 'gold_ingot'],
      ['gold_ingot', 'gold_ingot', 'gold_ingot'],
    ],
    output: 'golden_apple',
    materials: ['gold_ingot', 'melon_slice'],
    difficulty: 'hard',
  },
  {
    id: 'ender_eye',
    type: 'shapeless',
    label: 'Eye of Ender',
    ingredients: ['ender_pearl', 'blaze_powder'],
    output: 'ender_eye',
    difficulty: 'hard',
  },
  {
    id: 'snow_golem',
    type: 'shaped',
    label: 'Snow Golem',
    pattern: [
      [null, 'pumpkin', null],
      [null, 'snow_block', null],
      [null, 'snow_block', null],
    ],
    output: 'snow_golem',
    materials: ['pumpkin', 'snow_block'],
    difficulty: 'hard',
  },
];

export default recipes;
